version: '2'
services:
  # nginx:
  #   image: "nginx:1.13"
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   restart: always

  app:
    build: "."
    image: flowdocker/solidus:0.2.0
    # env_file: ./config/docker/.env
    # links:
    #   - "nginx"
    ports:
      - "3000:3000"
    command: bundle exec rails s -e production -p 3000 -b '0.0.0.0'
