default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: 5

# DB connection is provided by URL from ENV
# and this settings allows us to test prod env localy
production:
  <<: *default
  pool: 20
  url: <%= ENV.fetch('DB_URL') %>

development:
  <<: *default
  url: <%= ENV.fetch('DB_URL') %>

# provide your DB URL or use default one
test:
  <<: *default
  url: <%= ENV['DB_TEST_URL'] || 'postgres://localhost/flow_solidus_demo_test'%>
